CREATE TABLE IF NOT EXISTS ratings (
	id integer PRIMARY KEY,
	name varchar(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50) NOT NULL,
	description varchar,
	duration integer NOT NULL,
	release_date date,
	rating_id integer REFERENCES ratings
);

CREATE TABLE IF NOT EXISTS genres (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre (
	film_id integer REFERENCES films,
	genre_id integer REFERENCES genres
);

CREATE TABLE IF NOT EXISTS users (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(50) NOT NULL,
	login varchar(50) NOT NULL,
	name varchar(50),
	birthday date
);

CREATE TABLE IF NOT EXISTS friendship (
	user_id integer REFERENCES users,
	friend_id integer REFERENCES users
);

CREATE TABLE IF NOT EXISTS film_likes (
	user_id integer REFERENCES users,
	film_id integer REFERENCES films
);